@startuml FDX_Web_Journey_Sequence

title \n\n\n

actor "End User" as PSU
participant "Data\nRecipient" as DR

box Amplify Fusion #6FA8DC
participant "API\nGateway" as API_GATEWAY
participant "Consent\nManagement" as CONSENT
participant "Core Banking \nConnector" as CBC
end box

box Identity and Access Control #94c47d
participant "Identity Management\n---\nAuthorization Server" as IAM
participant "Consent Grant\nApp" as CONSENT_WEB
end box

box Core Banking Applications #d5a6bd
participant "Banking\nIdentity\nProvider" as ASPSP_WEB
participant "Banking\nSystems" as ASPSP_API
end box

hide footbox
'skinparam defaultFontName Roboto
skinparam BoxPadding 20

note right of PSU
Overview
===
This diagram sh ows the end-to-end web journey for obtaining Consent and starting to collect
Account Information data. The goal is to place the components from the Architecture Overview
in context.
end note

== Part 1: DR Obtains End User Consent ==

note right of PSU
Obtaining Consent from the End User is usually outside the scope of technical standards. The
Customer Experience Guidelines in FDX informs how Consent should be displayed and obtained.
|||
The specifics of this process are therefore not shown here. The Data Recipient (DR) is
assumed to have implemented this within the guidelines specified.
end note

PSU -> DR: Indicate wish to share data
PSU <-- DR: Display "Intent"\ni.e. data to be accessed\nor payment to be made
PSU -> DR: Confirm intent
PSU <-- DR: Show bank selection screen
PSU -> DR: Confirm bank selection

== Part 2: DR Creates and Lodges "Intent" ==

note right of DR
With the consent of the End User obtained the DR can now call the 
Authorization Server API at the correct bank. Note at this point 
Consent is usual termed "Intent" as it has yet to be confirmed at the bank.
end note

DR -> DR: Create Intent payload

note right of DR
Send Push Authorization Request
|||
The par request MUST contain an authorization details parameter
|||
{
  "authorization_details": [
    {
      "type": "fdx_v1.0",
      "consentRequest": {
        "durationType": "ONE_TIME",
        "lookbackPeriod": 60,
        "resources": [
          {
            "resourceType": "ACCOUNT",
            "dataClusters": [
              "ACCOUNT_DETAILED",
              "TRANSACTIONS"
            ]
          }
        ]
      }
    }
  ]
}
end note

DR -> API_GATEWAY: ""POST /par "{"authorization_details":[{"type":"fdx_v1.0","consentRequest":"...."}]"""
API_GATEWAY -> API_GATEWAY: Validate certificate
API_GATEWAY -> IAM: ""POST /par "{"authorization_details":[{"type":"fdx_v1.0","consentRequest":"...."}]"""
API_GATEWAY <-- IAM: return request_uri
API_GATEWAY --> CONSENT: Create consent
API_GATEWAY <-- CONSENT: Consent created
DR <-- API_GATEWAY: return request_uri

== Part 3: User authentication, consent and authorization ==

note right of DR
Send Authorization Request
end note

DR -> IAM: ""GET /authorize&request_uri=""
IAM -> ASPSP_WEB: ""REDIRECT /login""
ASPSP_WEB -> PSU: ""USER login""
PSU --> ASPSP_WEB: ""200 OK {...}""
ASPSP_WEB --> CONSENT_WEB: Serve Consent and\nAccount Confirmation Screen
CONSENT_WEB --> PSU: Serve Consent and Account Confirmation Screen
PSU --> CONSENT_WEB: "Consent confirmation is correct
CONSENT_WEB --> CONSENT: Update consent resources and status
CONSENT --> CONSENT_WEB: Consent updated
CONSENT --> IAM: Redirect with success
IAM --> DR: ""200 OK {"code":"..."}""

note right of DR
The DR then obtains the Access Token using the Authorization Code
end note

DR -> IAM: ""POST /token""
IAM -> IAM: Verify Client
DR <- IAM: ""200 OK""\n""{"access_token": "..."}""

== Part 4: Request Data ==
note right of DR
**Account Information**
---
DRs use a generic endpoint for Account Information that covers all
account types (checking, credit card, loans, etc).
end note

DR -> API_GATEWAY: ""GET /fdx/{version}/core/accounts""
note right of API_GATEWAY
Validate Access Token
end note
API_GATEWAY --> API_GATEWAY: Verify Access Token claims
API_GATEWAY -> CBC: ""GET /fdx/{version}/core/accounts""
CBC -> ASPSP_API: ""GET /fdx/{version}/core/accounts""
ASPSP_API -> CBC: ""200 OK""\n""{"accounts": "..."}""
CBC -> API_GATEWAY: ""200 OK""\n""{"accounts": "..."}""
API_GATEWAY -> DR: ""200 OK""\n""{"accounts": "..."}""

@enduml