@startuml Mutual_Authentication_Sequence

title \n\n

participant "Third-Party\nApp" as TPP

box Open Banking APIs #e06666 
participant "API\nGateway" as API_GATEWAY
participant "API\nBuilder" as API_BUILDER
end box

box Identity and Access Control #94c47d
participant "Identity\nManagement" as IAM
end box

participant "Market\nCertificate\nAuthority" as CA
participant "Konsentus" as KON
participant "European\nOpen Banking\nMarkets" as EURO
' participant "JSON Web\nKey Set" as OBD_JWKS

box Core Banking Applications #d5a6bd
participant "Banking\nSystems" as ASPSP_API
end box

hide footbox
skinparam defaultFontName Roboto
skinparam BoxPadding 10

note right of TPP
This diagram shows the specifics of mutual authentication
as implemented in the open banking accelerator.
end note

TPP -> API_GATEWAY: Request protected endpoint
API_GATEWAY -> API_GATEWAY: Validate certificate chain

alt European Market

note right of API_GATEWAY
In PSD2 markets the solution can be
supported by Konsentus who provide
a pan-EU solution for checking both
certificate and TPP validity.
end note

API_GATEWAY -> KON: Request certification verification
KON -> KON: Resolve certificate\nprovenance
KON -> EURO: Verify certificate\nin market
KON <-- EURO: Response
API_GATEWAY <-- KON: Response

else Non-European Market

note right of API_GATEWAY
Non-PSD2 markets tend to implement more
traditional PKIs where validity is checked
using either OCSP or a CRL.
end note

API_GATEWAY -> CA: Check certificate status (OCSP/CRL)
API_GATEWAY <-- CA: Response
end opt

alt Certificate binding is enforced

note right of API_GATEWAY
Binding the Access Token to a given client
certificate is enforced through FAPI which
references [[https://datatracker.ietf.org/doc/html/rfc8705 RFC 8705]].
|||
To support this the API Gateway uses the
Access Token introspection endpoint to
retrieve the stored certificate fingerprint.
end note

API_GATEWAY -> IAM: Access Token\nintrospection
IAM -> IAM: Retrieve Access\nToken properties
API_GATEWAY <-- IAM: Response
API_GATEWAY -> API_GATEWAY: Calculate certificate\nfingerprint
API_GATEWAY -> API_GATEWAY: Compare stored and\ncalculated fingerprints
end alt

API_GATEWAY -> API_BUILDER: Request protected endpoint
API_BUILDER -> ASPSP_API: Request backend data or service
API_BUILDER <-- ASPSP_API: Response
API_GATEWAY <-- API_BUILDER: Response
TPP <-- API_GATEWAY: Response

@enduml