@startuml Mutual_Authentication_Sequence

title \n\n

participant "Data\nRecipient" as DR

box Amplify Fusion #6FA8DC
participant "API\nGateway" as API_GATEWAY
participant "Core Banking\nConnector" as CBC
end box

box Identity and Access Control #94c47d
participant "Authorization\nServer" as IAM
end box

participant "Market\nCertificate\nAuthority" as CA
' participant "JSON Web\nKey Set" as OBD_JWKS

box Core Banking Applications #d5a6bd
participant "Banking\nSystems" as ASPSP_API
end box

hide footbox
'skinparam defaultFontName Roboto
skinparam BoxPadding 10

note right of DR
This diagram shows the specifics of mutual authentication
as implemented in the open banking accelerator.
end note

DR -> API_GATEWAY: Request protected endpoint
API_GATEWAY -> API_GATEWAY: Validate certificate chain
API_GATEWAY -> CA: Check certificate status (OCSP/CRL)
API_GATEWAY <-- CA: Response

alt Certificate binding is enforced

note right of API_GATEWAY
Binding the Access Token to a given client
certificate is enforced through FAPI which
references [[https://datatracker.ietf.org/doc/html/rfc8705 RFC 8705]].
|||
To support this the API Gateway uses the
JWT claims to retrieve the stored 
certificate fingerprint.
end note

API_GATEWAY -> IAM: Call JWKS Endpoint to validate JWT access token
API_GATEWAY <-- IAM: Return JWKS
API_GATEWAY -> API_GATEWAY: Get claims from JWT
API_GATEWAY -> API_GATEWAY: Calculate certificate\nfingerprint
API_GATEWAY -> API_GATEWAY: Compare stored and\ncalculated fingerprints
end alt

API_GATEWAY -> CBC: Request protected endpoint
CBC -> ASPSP_API: Request backend data or service
CBC <-- ASPSP_API: Response
API_GATEWAY <-- CBC: Response

@enduml