@startuml Mutual_Authentication_Sequence

title \n\n

participant "Data\nRecipient" as DR

box Infrastructure #6FA8DC
participant "Ingress\nController" as INGRESS
participant "API\nGateway" as API_GATEWAY
end box

box Open Banking APIs #e06666 
'participant "API\nGateway" as API_GATEWAY
participant "Backend\nIntegration\nApplication" as BIA
end box

box Identity and Access Control #94c47d
participant "Identity\nManagement" as IAM
end box

participant "Market\nCertificate\nAuthority" as CA
' participant "JSON Web\nKey Set" as OBD_JWKS

box Core Banking Applications #d5a6bd
participant "Banking\nSystems" as ASPSP_API
end box

hide footbox
skinparam defaultFontName Roboto
skinparam BoxPadding 10

note right of DR
This diagram shows the specifics of mutual authentication
as implemented in the open banking accelerator.
end note

DR -> INGRESS: Request protected endpoint
INGRESS -> INGRESS: Validate certificate chain
INGRESS -> API_GATEWAY: Request protected endpoint
API_GATEWAY -> CA: Check certificate status (OCSP/CRL)
API_GATEWAY <-- CA: Response

alt Certificate binding is enforced

note right of API_GATEWAY
Binding the Access Token to a given client
certificate is enforced through FAPI which
references [[https://datatracker.ietf.org/doc/html/rfc8705 RFC 8705]].
|||
To support this the API Gateway uses the
Access Token introspection endpoint to
retrieve the stored certificate fingerprint.
end note

API_GATEWAY -> IAM: Access Token\nintrospection
IAM -> IAM: Retrieve Access\nToken properties
API_GATEWAY <-- IAM: Response
API_GATEWAY -> API_GATEWAY: Calculate certificate\nfingerprint
API_GATEWAY -> API_GATEWAY: Compare stored and\ncalculated fingerprints
end alt

API_GATEWAY -> BIA: Request protected endpoint
BIA -> ASPSP_API: Request backend data or service
BIA <-- ASPSP_API: Response
API_GATEWAY <-- BIA: Response
INGRESS <-- API_GATEWAY: Response
DR <-- INGRESS: Response

@enduml